name: versioning
on:
  push:
    branches:
      - main
jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
      # Updates the list-v* git tag to version `plugins.json`.
      # Consumers must use the tag-specific deploy URL:
      #   list-v*--netlify-plugins.netlify.app/plugins.json
      # This versions the syntax of `plugins.json`, not its contents.
      # The contents, i.e. the list of plugins, is versioned using the v*
      # git tag instead, which also comes with GitHub and npm releases.
      # For example:
      #  - Changing a property name in `plugins.json` for all plugins
      #    is a syntax breaking change (list-v* tag)
      #  - Releasing a breaking change for a specific plugin in `plugins.json`
      #    is a contents breaking change (v* tag + GitHub release + npm release)
      - name: Update branch
        run: |
          git tag --force list-v2
          git push --force --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
